// @generated by build.rs - do not edit manually
// Source: https://github.com/github/gitignore (MIT license)

#[derive(Debug, Clone)]
pub struct GitignoreTemplate {
    pub id: &'static str,
    pub name: &'static str,
    pub content: &'static str,
}

pub const GITIGNORE_TEMPLATES: &[GitignoreTemplate] = &[
    GitignoreTemplate {
        id: "node",
        name: "Node",
        content: include_str!("../templates/node.gitignore"),
    },
    GitignoreTemplate {
        id: "python",
        name: "Python",
        content: include_str!("../templates/python.gitignore"),
    },
    GitignoreTemplate {
        id: "rust",
        name: "Rust",
        content: include_str!("../templates/rust.gitignore"),
    },
    GitignoreTemplate {
        id: "go",
        name: "Go",
        content: include_str!("../templates/go.gitignore"),
    },
    GitignoreTemplate {
        id: "java",
        name: "Java",
        content: include_str!("../templates/java.gitignore"),
    },
    GitignoreTemplate {
        id: "c++",
        name: "C++",
        content: include_str!("../templates/c++.gitignore"),
    },
    GitignoreTemplate {
        id: "ruby",
        name: "Ruby",
        content: include_str!("../templates/ruby.gitignore"),
    },
    GitignoreTemplate {
        id: "swift",
        name: "Swift",
        content: include_str!("../templates/swift.gitignore"),
    },
    GitignoreTemplate {
        id: "kotlin",
        name: "Kotlin",
        content: include_str!("../templates/kotlin.gitignore"),
    },
    GitignoreTemplate {
        id: "scala",
        name: "Scala",
        content: include_str!("../templates/scala.gitignore"),
    },
    GitignoreTemplate {
        id: "elixir",
        name: "Elixir",
        content: include_str!("../templates/elixir.gitignore"),
    },
    GitignoreTemplate {
        id: "vue",
        name: "Vue",
        content: include_str!("../templates/vue.gitignore"),
    },
    GitignoreTemplate {
        id: "nextjs",
        name: "Next.js",
        content: include_str!("../templates/nextjs.gitignore"),
    },
    GitignoreTemplate {
        id: "rails",
        name: "Rails",
        content: include_str!("../templates/rails.gitignore"),
    },
    GitignoreTemplate {
        id: "laravel",
        name: "Laravel",
        content: include_str!("../templates/laravel.gitignore"),
    },
    GitignoreTemplate {
        id: "unity",
        name: "Unity",
        content: include_str!("../templates/unity.gitignore"),
    },
    GitignoreTemplate {
        id: "unrealengine",
        name: "Unreal Engine",
        content: include_str!("../templates/unrealengine.gitignore"),
    },
    GitignoreTemplate {
        id: "visualstudiocode",
        name: "VisualStudioCode",
        content: include_str!("../templates/visualstudiocode.gitignore"),
    },
    GitignoreTemplate {
        id: "jetbrains",
        name: "JetBrains",
        content: include_str!("../templates/jetbrains.gitignore"),
    },
    GitignoreTemplate {
        id: "vim",
        name: "Vim",
        content: include_str!("../templates/vim.gitignore"),
    },
    GitignoreTemplate {
        id: "emacs",
        name: "Emacs",
        content: include_str!("../templates/emacs.gitignore"),
    },
    GitignoreTemplate {
        id: "xcode",
        name: "Xcode",
        content: include_str!("../templates/xcode.gitignore"),
    },
    GitignoreTemplate {
        id: "visualstudio",
        name: "VisualStudio",
        content: include_str!("../templates/visualstudio.gitignore"),
    },
    GitignoreTemplate {
        id: "macos",
        name: "macOS",
        content: include_str!("../templates/macos.gitignore"),
    },
    GitignoreTemplate {
        id: "windows",
        name: "Windows",
        content: include_str!("../templates/windows.gitignore"),
    },
    GitignoreTemplate {
        id: "linux",
        name: "Linux",
        content: include_str!("../templates/linux.gitignore"),
    },
    GitignoreTemplate {
        id: "terraform",
        name: "Terraform",
        content: include_str!("../templates/terraform.gitignore"),
    },
    GitignoreTemplate {
        id: "dotnet",
        name: ".NET",
        content: include_str!("../templates/dotnet.gitignore"),
    },
    GitignoreTemplate {
        id: "cmake",
        name: "CMake",
        content: include_str!("../templates/cmake.gitignore"),
    },
    GitignoreTemplate {
        id: "gradle",
        name: "Gradle",
        content: include_str!("../templates/gradle.gitignore"),
    },
    GitignoreTemplate {
        id: "maven",
        name: "Maven",
        content: include_str!("../templates/maven.gitignore"),
    },
    GitignoreTemplate {
        id: "bun",
        name: "Bun",
        content: include_str!("../templates/bun.gitignore"),
    },
];

pub fn get_all_templates() -> Vec<GitignoreTemplate> {
    GITIGNORE_TEMPLATES.to_vec()
}

pub fn get_template(id: &str) -> Option<&'static GitignoreTemplate> {
    GITIGNORE_TEMPLATES.iter().find(|t| t.id == id)
}